### PR TITLE
fix some build errors about isnan and isinf, not used std namespace

### PR DESCRIPTION
**Pull request by Frank-gh**
### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Review by LINxiansheng — APPROVED** [review]
Approve

**Comment by Frank-gh** [comment]
image

**Comment by LINxiansheng** [comment]
Already fix in an internal update.
Thanks for your contribution.

**Pull request closed without merging**
