### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by wshonline**
### What changes were proposed in this pull request?
Fixed typos in ob_election_timer.cpp
team: push_d_

### Why are the changes needed?
issue: #457

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by wshonline** [comment]
See you plan Merge, but have not yet done. Hope you notice this, thanks.

**Comment by LINxiansheng** [comment]
> Merge

Sorry for the late.

Although you just change some annotations, we need do a lot of test the diff because the files are belong to source code.

**Comment by LINxiansheng** [comment]
Thanks for your contribution.

**Pull request merged**
