### PR TITLE
window_function removal and segment_tree

### PR DESCRIPTION
**Pull request by jinghehehe**
### What changes were proposed in this pull request?
add 2 aggregation method in window function: Removable Cumulative Aggregation and Segment Tree Aggregation. 

### Why are the changes needed?
when compute frame's aggregation value in window function, if interval is iteration interval, window function only use naive aggregation, we add removable cumulative aggregation for supporting iteration interval. If interval concludes variable, we add segment tree aggregation to improve performance.

### Will break the compatibility? How if so?
No.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
add test file: test/mysql_test/test_suite/window_function/t/removal_segment_tree.test
add result file:test/mysql_test/test_suite/window_function/r/mysql/removal_segment_tree.result

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by jinghehehe** [comment]
@LINxiansheng hello, I resubmit a pr for #291, now I closed that pr.

**Comment by LINxiansheng** [comment]
> @LINxiansheng hello, I resubmit a pr for #291, now I closed that pr.

Got it and I will review the pr as soon as possible.

**Review by LINxiansheng — APPROVED** [review]

**Pull request closed without merging**
