### PR TITLE
fix mispelled cancel

### PR DESCRIPTION
**Pull request by LLThomas**
### What changes were proposed in this pull request?

Fixed typos in ob_election_timer.cpp

team: LLThomas

### Why are the changes needed?

issue: #267

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
Please sign the cla.

**Comment by LLThomas** [comment]
> Please sign the cla.

Done.

**Comment by LINxiansheng** [comment]
Thanks for your contribution.

**Pull request merged**
