### PR TITLE
fix mispelled executor

### PR DESCRIPTION
**Pull request by hey-kong**
### What changes were proposed in this pull request?

Fixed typos in ob_clog_mgr.cpp

### Why are the changes needed?

issue #522

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by hey-kong** [comment]
@LINxiansheng PTAL~

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
> @LINxiansheng PTAL~

Sorry it is my fault.
Originally I think it direct the class to the 'ob_log_external_executor_v2' but I search the log and find that the 'v2' is not a proper expression.

**Comment by LINxiansheng** [comment]
Thanks for your contribution.

**Pull request merged**
