### PR TITLE
ob_ilog_storage.cpp with misspelled word

### PR DESCRIPTION
**Pull request by zaiwind**
What changes were proposed in this pull request?

Team github id :blazersEvan
Fix typos in src/clog/ob_ilog_storage.cpp 

Why are the changes needed?

issue [#444](https://github.com/oceanbase/oceanbase/issues/444)

Will break the compatibility? How if so?

Does this PR introduce any user-facing change?

How was this patch tested?

Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
Why close it, it's right.

**Comment by LINxiansheng** [comment]
I merge it, thanks for your contribution

**Comment by zaiwind** [comment]
thanks

**Pull request merged**
