### PR TITLE
fix bug：连续多行的单行注释报错 bug #783

### PR DESCRIPTION
**Pull request by akaError**
### What changes were proposed in this pull request?

add rule for comment ('#','--') when ObParser::split_multiple_stmt split sql 

### Why are the changes needed?

compatible with mysql

### Will break the compatibility? How if so?

no

### Does this PR introduce any user-facing change?
no

no

### How was this patch tested?

create database q5;
use q5
create table t1(c1 int, c2 int, c3 int);
create table t2(c1 int, c2 int, c3 int);
show tables;

insert into t1 (c1,c2,c3) values (1,2,30);

select * from t1
union all
-- xxx;
-- xxy
select * from t2
;

select * from t1
union all
#ttx;
#tty
select * from t2;

select * from t1
#中文更有问题了;报错;
;

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by watchpoints** [comment]
the format of code  eg ObSqlCtx& context

**Comment by LINxiansheng** [comment]
Thanks for your contribution.

**Pull request merged**
