### PR TITLE
Enable IAA for accelerate defalte compression and decompression for OB 4.0

### PR DESCRIPTION
**Pull request by xtangxtang**
### What changes were proposed in this pull request?

This Pull Request is migrated from PR (https://github.com/oceanbase/oceanbase/pull/1044) for OB 4.0, the PR (https://github.com/oceanbase/oceanbase/pull/1044) is for OB 3.1.X and is closed.

Intel® In-Memory Analytics Accelerator (Intel® IAA) is a hardware accelerator available in the upcoming generation of Intel® Xeon® Scalable processors ("Sapphire Rapids"). Its goal is to speed up common operations in analytics like data (de)compression and filtering.  This PR is to accelerate the Oceanbase deflate compression/decompression performance with IAA

### Why are the changes needed?

There are several cases that Oceanbase will do lz4/zstd compression, like building index, OLAP with TPCH and OLTP with Sysbench. From the 'perf' tool view, it shows that the lz4/zstd compression is the hotspot, like:

image

Also when Oceanbase do major compaction, the lz4 compression consumes a lot of CPU time:

image

After we replace the lz4 compression by IAA, Oceanbase can speedup the compression/decompression

### The Dependency

This PR depends on QPL library. Please follow the steps  to install the QPL lib

使用龙蜥社区的QPL代码。

- 安装依赖包

> yum install nasm libuuid libuuid-devel cmake make libudev-devel yasm gflags gflags-devel

 Shape7

- 下载代码

```
cd $WORK\_DIR

git clone  https://gitee.com/anolis/cloud-qpl/

cd cloud-qpl

git submodule init

git submodule update

```
 Shape8

- 编译USDM所依赖的头文件和库，并安装内核组件usdm\_drv.ko。

```
cd $WORK\_DIR/cloud-qpl/ third-party

sh build\_qat.sh
```

 Shape9

- 编译QPL库

cd $WORK\_DIR/cloud-qpl

```
mkdir build

cd build 

cmake -DCMAKE\_BUILD\_TYPE=Release -DCMAKE\_INSTALL\_PREFIX=../../qpl\_lib ..

make -j

make install

```
 Shape10

- After compile the QPL lib, Oceanbase should package the libqpl.a, libusdm_drv.a and include/qpl in the RPM package and put it on [http://mirrors.aliyun.com/](http://mirrors.aliyun.com/)

### Will break the compatibility? How if so?

The QPL compress/decompress logic is only available for x86. For other platform like ARM, the QPL functionality is unvisibale for the user. So the QPL code is just compiled for X86 platform. 

### Does this PR introduce any user-facing change?
 N/A

### How was this patch tested?

N/A

### Checklist

- [ X] I've run the tests to see all new and existing tests pass.
- [ X] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ X] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by hnwyllmm** [comment]
How can I get the library libusdm_drv.a?

**Comment by hnwyllmm** [comment]
There are some problems of security about zlib 1.2.7, so please upgrade the zlib to 1.2.13

**Comment by xtangxtang** [comment]
> How can I get the library libusdm_drv.a?
 * download the clould-qpl from "git clone  https://gitee.com/anolis/cloud-qpl/" 
 * "cd $WORK_DIR/cloud-qpl/third-party" and "sh build_qat.sh"

**Comment by xtangxtang** [comment]
> There are some problems of security about zlib 1.2.7, so please upgrade the zlib to 1.2.13

We will align to the zlib 1.2.13

**Comment by hnwyllmm** [comment]
I build the qpl and qat libraries successfully and it works on my machine.
image

**Comment by hnwyllmm** [comment]
I think it's better we can know the method that qpl compressor really use, such as hardware accelerate, qpl software and original zlib. But I have no idea about the way of representation right now.

**Comment by hnwyllmm** [comment]
I got some errors like below when I compile unittest and I am working on it:
```
[ 40%] Linking CXX shared library liboceanbase.so
ld.lld: error: duplicate symbol: adler32
>>> defined at adler32.c:69 (./deps/oblib/src/lib/compress/zlib/zlib_src/adler32.c:69)
>>>            ../../deps/oblib/src/lib/compress/zlib/CMakeFiles/zlib.dir/zlib_src/adler32.c.o:(adler32)
>>> defined at adler32.c:74 (./deps/oblib/src/lib/compress/zlib_lite/zlib_lite_src/adler32.c:74)
>>>            ../../deps/oblib/src/lib/compress/zlib_lite/CMakeFiles/zlib_lite.dir/zlib_lite_src/adler32.c.o:(.text.adler32+0x0)
```

**Review by hnwyllmm — APPROVED** [review]
LGTM

**Comment by hnwyllmm** [comment]
merged by bd4823fae98c084d8fcf324c2224e14a2f9793f8

**Pull request closed without merging**
