### PR TITLE
add default engine for TABLES

### PR DESCRIPTION
**Pull request by caifeizhi**
### What changes were proposed in this pull request?
change the default engine for TABLES

### Why are the changes needed?

close https://github.com/oceanbase/oceanbase/issues/756

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by whhe** [comment]
You can link a issue by a keyword like `close`
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by caifeizhi** [comment]
> You can link a issue by a keyword like `close` https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

edited

> You can link a issue by a keyword like `close` https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

edited, thanks

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
Thanks for your contribution.

**Pull request merged**
