### PR TITLE
 set the data_length to the new length even if buffer_size is 0 

### PR DESCRIPTION
**Pull request by xiaoleizi2016**
### Why are the changes needed?
fix issue #1027 

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by watchpoints** [comment]
提交重复了

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
我是比较同意这个修改，不过能不能帮忙加一个单测覆盖一下这个场景。

**Comment by xiaoleizi2016** [comment]
> 
good suggestion

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
In the internal review, we do not fix it when no bug occurs by it.

**Pull request closed without merging**
