### PR TITLE
ob_batch_submit_task.cpp with misspelled word #456

### PR DESCRIPTION
**Pull request by a920264845**
### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by LINxiansheng** [comment]
Sorry, it is correct.
'DTask' means 'Disk Task'

**Comment by a920264845** [comment]
1

**Comment by a920264845** [comment]
have sighed the cla.
please recheck
thanks

**Comment by LINxiansheng** [comment]
I think the issue is not a correct issue, and the pr is not necessary.

**Pull request closed without merging**
