### PR TITLE
Fix typo error: transfomer -> transformer

### PR DESCRIPTION
**Pull request by Leozki**
### What changes were proposed in this pull request?
fix type error

### Why are the changes needed?
#654

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by LINxiansheng** [comment]
It is same to the #669 and I will merge the #669 and add you the the together authors.

**Comment by Leozki** [comment]
> It is same to the #669 and I will merge the #669 and add you the the together authors.

Hi,The typo error is in two different files
#669 docs/docs/docs-cn/5.overview/7.sql-engine-1/1.sql-request-execution-process-1.md
#671 docs/docs/docs-cn/5.overview/7.sql-engine-1/6.sql-optimization-guide/1.sql-request-execution-process-2.md

**Comment by LINxiansheng** [comment]
> > It is same to the #669 and I will merge the #669 and add you the the together authors.
> 
> Hi,The typo error is in two different files #669 docs/docs/docs-cn/5.overview/7.sql-engine-1/1.sql-request-execution-process-1.md #671 docs/docs/docs-cn/5.overview/7.sql-engine-1/6.sql-optimization-guide/1.sql-request-execution-process-2.md

Sorry, I will merge it later.

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Pull request merged**
