### PR TITLE
replace macro:TO_STIRING_KV with function: to_string

### PR DESCRIPTION
**Pull request by tushicheng**

### CODE REVIEW

**Comment by SanmuWangZJU** [comment]
What is the purpose of replace TO_STRING_KV to to_string? Personally feel that this modification is meaningless

**Comment by SanmuWangZJU** [comment]
What is the purpose of replacing TO_STRING_KV with to_string? Personally, I feel that this modification is meaningless

**Comment by SanmuWangZJU** [comment]
What is the purpose of replace TO_STRING_KV to to_string? Personally feel that this modification is meaningless

**Comment by simonjoylet** [comment]
I do NOT think this replacement is necessary.
I will not approve it.

**Pull request closed without merging**
