### PR TITLE
fix typos "arugment->argument"[issue 507]

### PR DESCRIPTION
**Pull request by tuhahaha**
### What changes were proposed in this pull request?

Fixed typos for "arugment"

### Why are the changes needed?

[issue 507]

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by LINxiansheng** [comment]
please sign the cla.

**Comment by WangYuanZhen123123** [comment]
have sighed the cla.

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Pull request merged**
