### PR TITLE
improve README.md

### PR DESCRIPTION
**Pull request by caicancai**
### Task Description
 Supports intra-city/remote disaster recovery, enabling multi-activity in multiple locations and zero data loss.

### Solution Description

Corresponds to Chinese

### CODE REVIEW

**Comment by caicancai** [comment]
@hnwyllmm Thank you for your answer. I submitted a PR again. It is true that the email address was wrong. I am sorry for causing trouble to you.

**Comment by caicancai** [comment]
close: #1550

**Review by hnwyllmm — APPROVED** [review]
LGTM

**Comment by hnwyllmm** [comment]
The pull request is merging now, so please don't touch it any more.

**Comment by caicancai** [comment]
> The pull request is merging now, so please don't touch it any more.

Thank you for your reminder, because I seemed to have seen that the cli failed before, but I think this situation should not happen to me.

**Comment by hnwyllmm** [comment]
There are only building cases here.
We'll fix the CI issue a few days later and sorry for boring you.

**Pull request merged**
