### PR TITLE
oceanbase can run in low memory system now

### PR DESCRIPTION
**Pull request by hnwyllmm**
MINI_MEM_LOWER is the hard limit of memory.

### Why are the changes needed?
Built with this patch and then oceanbase can run in a system with lower memory such as 8g.

### Will break the compatibility? How if so?
no

### Does this PR introduce any user-facing change?
no

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by watchpoints** [comment]
now is 4G?

**Comment by hnwyllmm** [comment]
> now is 4G?

is not merged yet

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Pull request merged**
