### PR TITLE
resolve issue#618

### PR DESCRIPTION
**Pull request by zhouhuahui**
resolve issue#618

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by zhouhuahui** [comment]
this pr updated src/sql/engine/expr/ob_expr_remainder.cpp in line284 and line 291 for issue#618

**Review by LINxiansheng — APPROVED** [review]
LGTM, please sign the cla

**Comment by LINxiansheng** [comment]
Thanks for your contribution.

**Pull request merged**
