### PR TITLE
fix floating point number compare

### PR DESCRIPTION
**Pull request by Taylor-lagrange**
floating-point expressions shall not be directly or indirectly tested for equality or inequality

### What changes were proposed in this pull request?

floating-point expressions shall not be directly or indirectly tested for equality or inequality

### Why are the changes needed?

floating-point expressions shall not be directly or indirectly tested for equality or inequality

### Will break the compatibility? How if so?

no

### Does this PR introduce any user-facing change?

no

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by Taylor-lagrange** [comment]
[#](https://github.com/oceanbase/oceanbase/issues/1041)

**Comment by Taylor-lagrange** [comment]
https://github.com/oceanbase/oceanbase/issues/1041

**Comment by akaError** [comment]
it would be hard to count many 0, much best can be like "const double EPSINON = 1e-14;"

**Comment by Taylor-lagrange** [comment]
> it would be hard to count many 0, much better can be like "const double EPSINON = 1e-14;"

It has been fixed.

**Pull request merged**
