### PR TITLE
fix the alloc NULL bug of issue #601

### PR DESCRIPTION
**Pull request by JameyWoo**
### What changes were proposed in this pull request?

Fixed a bug where null pointer access may occur when alloc is NULL. Added a judgment on whether alloc is a null pointer.

### Why are the changes needed?

See the issue #601 

### Will break the compatibility? How if so?

No.

### Does this PR introduce any user-facing change?

No.

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by JameyWoo** [comment]
@LINxiansheng Hello, could you please take a moment to review my code? Thanks.

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
> @LINxiansheng Hello, could you please take a moment to review my code? Thanks.

I'm coming

**Pull request closed without merging**
