### PR TITLE
Optimize sort performance in index construction

### PR DESCRIPTION
**Pull request by zeminzhou**
### What changes were proposed in this pull request?
1.  Realization of sorting algorithm through intel extended instruction set AVX512(src/storage/ob_avx512_sort.h).
2. This sorting algorithm is combined with “Memcomparable format” and applied to the index construction process.
3. In index construction process, replace ObStoreRow with the new data structure ObSortRow.

1. new sort algorithm ("src/storage/ob_avx512_sort.h)
2. new struct ObSortRow("src/storag/ob_i_store.h)
3. add method make_sort_key for ObObj ("deps/oblib/src/common/object/ob_object.cpp").
### Why are the changes needed?

1. std::sort is slow.
2. In the process of constructing the index, the ObStoreRow used for sorting has too many useless fields, wasting space.

### Does this PR introduce any user-facing change?

NO

### Checklist

- [x] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by LINxiansheng** [comment]
The pull request lack some test to verify.
Thanks for your contribution.

**Comment by Charles0429** [comment]
This pull request has further things to do:
1.  support encoding of all data types and collations, and the current implementation lack unit test to test its encoding's rightness.
2. currently, this review only accelerates the sort process of local index, if we want to support global index, we need to do something to make this sorting algorithm work with the automatic memory management, because the sorting algorithm need to alloc as much memory as the original data, and the memory address must be continuously.

**Comment by xtangxtang** [comment]
I add a patch to fix the get_pivot bug for "src/storage/ob_avx512_sort.cpp". The patch is https://github.com/zeminzhou/oceanbase/compare/avx512-sort...xtangxtang:patch-1.

**Comment by xtangxtang** [comment]
> This pull request has further things to do:
> 
> 1. support encoding of all data types and collations, and the current implementation lack unit test to test its encoding's rightness.
> 2. currently, this review only accelerates the sort process of local index, if we want to support global index, we need to do something to make this sorting algorithm work with the automatic memory management, because the sorting algorithm need to alloc as much memory as the original data in worst case, and the memory address must be continuously.

Hi Charles. I did a performance test with this pull request code. The workload is SSB. I load 30G data and run "create index I_L_ORDERKEY on lineitem(l_orderkey) local; " The avx512 can speedup about 20% latency. So for the first thing we should do is to do some unit test?

**Pull request closed without merging**
