### PR TITLE
fix: typo for word `has`

### PR DESCRIPTION
**Pull request by FanBB2333**
### What changes were proposed in this pull request?
Some wrong typos in comments and log info are corrected.

### Why are the changes needed?
It would just influence the log format and comments.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by FanBB2333** [comment]
> /merge

It there anything I can do for this pr? It looks stuck.

**Comment by wayyoungboy** [comment]
> > /merge
> 
> It there anything I can do for this pr? It looks stuck.

We will deal with this as soon as possible

**Comment by FanBB2333** [comment]
> > > /merge
> > 
> > 
> > It there anything I can do for this pr? It looks stuck.
> 
> We will deal with this as soon as possible

Thanks a lot!

**Comment by LINxiansheng** [comment]
Some conflicts. I fix it and set you are the author. 4f4ce88cca0420eba80a90159c49fc730351f8b7
close

**Pull request closed without merging**
