### PR TITLE
Remove duplicate codes in ObBloomFilterBuildTask::build_bloom_filter

### PR DESCRIPTION
**Pull request by ScienJus**
### What changes were proposed in this pull request?

There are some duplicate codes in ObBloomFilterBuildTask::build_bloom_filter, It seems that there were some problems in resolving the merge conflict.

Please confirm whether it is `meta.schema_->rowkey_column_number_` or `meta.meta_->rowkey_column_number_`.(If there is a merge conflict, it is more likely to be the `meta.schema_->rowkey_column_number_`, because the second change deletes the `scanner`, then the first change should be a modification of the `rowkey_cnt_`)

### Will break the compatibility? How if so?

No, it won't.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

N/A

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [x] I've informed the technical writer about the documentation change if necessary.

### CODE REVIEW

**Comment by saltonz** [comment]
I believe `meta.schema_->rowkey_column_number_ ` and `meta.meta_->rowkey_column_number_` would always have same value

**Comment by ScienJus** [comment]
After five months, this PR is still open and no one is reviewing =0=

**Review by simonjoylet — APPROVED** [review]

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by simonjoylet** [comment]
> After five months, this PR is still open and no one is reviewing =0=

Thank you for your contribution. I'm sorry that we have forgot to review your code. We will review all pull requests in the list instead of only checking the new notifications.

**Pull request merged**
