### PR TITLE
Fix Pull Request overrides again

### PR DESCRIPTION
**Pull request by dsh0416**
535864943331c74abad6f466d36dd44d20dc28ff overrides #809 AGAIN!

related commits:
535864943331c74abad6f466d36dd44d20dc28ff
#809 
88693a523a6a860be4d709ca62224fbe2de30dff
#798 
#796

### CODE REVIEW

**Comment by dsh0416** [comment]
Would it be a better idea if we could have a CI proces that would scan all broken links happened in the documentation files. This would be either better fix such issues and better serve the current rapidly growing oceanbase documentation development.

**Comment by LINxiansheng** [comment]
Sorry and I found why the error happened.

**Comment by LINxiansheng** [comment]
> Would it be a better idea if we could have a CI proces that would scan all broken links happened in the documentation files? This would be either better fix such issues and better serve the current rapidly growing oceanbase documentation development.

Thanks for your contribution.
I think it is not necessary because we can fix this errors with easy efforts.

**Review by LINxiansheng — APPROVED** [review]
LGTM

**Comment by LINxiansheng** [comment]
643214fe3a705822e0b4cf6e25e0f642b35d762c

**Pull request closed without merging**
