### PR TITLE
update gitsubmodule

### PR DESCRIPTION
**Pull request by yetist**
使用最新提交，保持 `deps/logmessage` 子模块同步。

### CODE REVIEW

**Comment by LINxiansheng** [comment]
Do not need to update the gitsubmodule files and just use git submodule update can fix it.

**Comment by yetist** [comment]
Don't you see that this is an obvious mistake? 
There is no such commit in the [oblogmsg](https://github.com/oceanbase/oblogmsg/commits/master
): 4f9e63f635e841e457cd1d6f28d80ef2e196ebea
```
509d86f (HEAD, origin/master, origin/HEAD, master) change __thread lmb to LogMsgBuf class,set it in toString
b290b90 hidden symbols in LogMsgBuf.cpp,set HIDDEN_DMB_SYMBOLS = true to enable it
482cef3 add crc32 verification
79905a7 format README.md,add blank space
9428651 formated README.md
762aa44 install oblogmsgConfigVersion.cmake
c3ebae7 init push
```

**Comment by LINxiansheng** [comment]
> Don't you see that this is an obvious mistake? There is no such commit in the [oblogmsg](https://github.com/oceanbase/oblogmsg/commits/master): 4f9e63f635e841e457cd1d6f28d80ef2e196ebea
> 
> ```
> 509d86f (HEAD, origin/master, origin/HEAD, master) change __thread lmb to LogMsgBuf class,set it in toString
> b290b90 hidden symbols in LogMsgBuf.cpp,set HIDDEN_DMB_SYMBOLS = true to enable it
> 482cef3 add crc32 verification
> 79905a7 format README.md,add blank space
> 9428651 formated README.md
> 762aa44 install oblogmsgConfigVersion.cmake
> c3ebae7 init push
> ```
I saw the hash.

It is a has value in the internal commit.
You can remove the submodule and clean the git cache and then get the correct hash of gitsubmodule.

**Comment by yetist** [comment]
> I saw the hash.
> 
> It is a has value in the internal commit. You can remove the submodule and clean the git cache and then get the correct hash of gitsubmodule.

Maybe `4f9e63f635e841e457cd1d6f28d80ef2e196ebea` is the value in the internal commit. However, in the `.gitmodule` file, the repo url of the submodule is `https://github.com/oceanbase/oblogmsg.git`, so it is not used at all.

https://github.com/oceanbase/oceanbase/blob/3d79cacb37012cf61b7cb8faf00d9a6bb152bcd1/.gitmodules#L3

**Comment by LINxiansheng** [comment]
In the new version(4.0), the logmsg source file is installed by rpm instead of git submodule.

**Pull request closed without merging**
